### ISSUE TITLE
Still Functional?

### ISSUE THREAD

**Issue by SneakBots** [chinhtle/reserve-tfl#2]
Tried to run the script and got the following error, could you tell me if the script is deprecated or if it was an issue on my end?

`Exception in thread Thread-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "reserve_tfl.py", line 163, in run_reservation
    r = ReserveTFL()
  File "reserve_tfl.py", line 76, in __init__
    self.driver = webdriver.Chrome(options=options)
TypeError: __init__() got an unexpected keyword argument 'options'`

**Comment by Parker999** [comment]
1: you might want to upgrade your python to 3.8
